# Generated by Django 4.0.3 on 2022-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('house', 'House'), ('condo', 'Condo'), ('town house', 'Townhouse')], default='house', max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], default='for sale', max_length=15),
        ),
    ]
