# Generated by Django 4.0.3 on 2022-03-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_bathrooms_alter_listing_home_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='main_photos',
            new_name='main_photo',
        ),
    ]
